const config = {
    "DISPLAY_TIME_CALIBRATION_TEST_POINT": 10000,
    "DISPLAY_TIME_CALIBRATION_POINT": 4000,
    "DISPLAY_TIME_CALIBRATION_INSTRUCTIONS": 10000,
    "DISPLAY_TIME_PERFORMANCE_TEST_INSTRUCTIONS": 10000,
    "NUM_TEST_POINTS": 10,
}

export default config