const config = {
    "DISPLAY_TIME_CALIBRATION_TEST_POINT": 1000,
    "DISPLAY_TIME_CALIBRATION_POINT": 1000,
    "DISPLAY_TIME_CALIBRATION_INSTRUCTIONS": 500,
    "DISPLAY_TIME_PERFORMANCE_TEST_INSTRUCTIONS": 500,
    "NUM_TEST_POINTS": 4,
    "SERVER_URL": "http://127.0.0.1:5000"
}

export default config