const config = {
    "DISPLAY_TIME_CALIBRATION_TEST_POINT": 2000,
    "DISPLAY_TIME_CALIBRATION_POINT": 2000,
    "DISPLAY_TIME_CALIBRATION_INSTRUCTIONS": 1000,
    "DISPLAY_TIME_PERFORMANCE_TEST_INSTRUCTIONS": 1000,
    "NUM_TEST_POINTS": 3,
}

export default config